export default {
  /**
   * AUTH ACTIONS
   */
  ATTEMPT_SIGN_IN: 'ATTEMPT_SIGN_IN',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  CANCEL_AUTH: 'CANCEL_AUTH',
  /**
   * USER ACTIONS
   */
  FETCH_USERS: 'FETCH_USERS',
  SET_USERS: 'SET_USERS',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  /**
   * RESTAURANT ACTIONS
   */
  FETCH_RESTAURANTS: 'FETCH_RESTAURANTS'
}